version: '3'
services:

  mysql:
   image: mysql:5.5
   network_mode: host
   restart: always
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: newsDb

  user-app: 
   build: userservice/
   image: saswata8/news_app:user-service
   restart: always
   network_mode: host
   ports:
     - "8089:8089"
   expose:
     - "8089"
   depends_on:
     - mysql
     
  news-app: 
   build: favouriteservice/
   image: saswata8/news_app:news-service
   restart: always
   network_mode: host
   ports:
     - "8082:8082"
   expose:
     - "8082"
   depends_on:
     - mysql
  
  angular:
    build: NewsappUI/
    image: saswata8/news_app:news-ui
    network_mode: host
    container_name: angular-docker
    ports:
      - "4200:4200"
